### ISSUE TITLE
cant build 

### ISSUE THREAD

**Issue by svarughese91** [GuyAvraham/expo-auth0-example-2020#4]
I am having issues trying to build this in expo:
 web  Failed to compile.
.../auth0-example/node_modules/react-native/Libraries/StyleSheet/processColor.js
Module not found: Can't resolve '../Utilities/Platform' in '.../auth0-example/node_modules/react-native/Libraries/StyleSheet'

When I try to run it in the ios simulator I get this error:
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-25 at 07 55 55](https://user-images.githubusercontent.com/18539023/85715337-5802b980-b6b9-11ea-94e2-8f9b5f2a58a9.png)

**Comment by GuyAvraham** [comment]
Hey @svarughese91 
You got "web" compilation error?
What command you run after git cloning the repo?

**Comment by svarughese91** [comment]
i ran npm start and then expo started and selected run in web browser

**Comment by GuyAvraham** [comment]
Yea, I can see it on my side as well. 
It was never adopted to run with expo-web...
